Algoritmo "semnome"
// 3 - Pedir para o usuário digitar quatro notas e imprimir na tela sua média aritmética.
Var
N1, N2, N3, N4, MEDIA :REAL
Inicio
  ESCREVAL("DIGITE QUATRO NOTAS:")
  ESCREVA("1° NOTA:")
  LEIA(N1)
  ESCREVA("2° NOTA:")
  LEIA(N2)
  ESCREVA("3° NOTA:")
  LEIA(N3)
  ESCREVA("4° NOTA:")
  LEIA(N4)
  MEDIA <- (N1+N2+N3+N4)/4
  ESCREVAL("A MÉDIA DAS NOTA É:", MEDIA)

Fimalgoritmo