algoritmo "21.07.2022"
//4) Faça um contador que conte de onde o usuário quiser até onde ele quiser.
var
ni,nf, cont :inteiro
inicio
  escreval("Digite o número inicial e final do contador.")
  escreva("N° INICIAL: ")
  leia(ni)
  escreva("N° FINAL: ")
  leia(nf)

  para cont de ni ate nf faca
    escreval(cont)
  fimpara
  para cont de ni ate nf passo -1 faca
    escreval(cont)
  fimpara
fimalgoritmo